name: Roshka Studios
description: Official site of Roshka Studios
meta_description: "Improving entertainment"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
paginate: 10
baseurl: 
email: 'roshkastudios@gmail.com'

# Plugins
plugins: 
  - jekyll-paginate